insert into attributes (description) values ('Color');
insert into attributes (description) values ('Collection');
insert into attributes (description) values ('Residential/Commercial');
insert into attributes (description) values ('Weight');
insert into attributes (description) values ('Length');
insert into attributes (description) values ('Depth');
insert into attributes (description) values ('Width');
insert into attributes (description) values ('Height');
insert into attributes (description) values ('Diameter');
insert into attributes (description) values ('Lead Law Compliant');
insert into attributes (description) values ('Watersense');
insert into attributes (description) values ('Water Efficient');
insert into attributes (description) values ('Gallon Per Minute');
insert into attributes (description) values ('Gpc');
insert into attributes (description) values ('Cal Green');
insert into attributes (description) values ('Ada');
insert into attributes (description) values ('Ansi Approved');
insert into attributes (description) values ('Approved For Commercial Use');
insert into attributes (description) values ('Asme Approved');
insert into attributes (description) values ('Asme Code');
insert into attributes (description) values ('Bodysprays Included');
insert into attributes (description) values ('Bridge Faucet');
insert into attributes (description) values ('Connection Size');
insert into attributes (description) values ('Connection Type');
insert into attributes (description) values ('Country Of Origin');
insert into attributes (description) values ('Csa Approved');
insert into attributes (description) values ('Csa Code');
insert into attributes (description) values ('Diverter Included');
insert into attributes (description) values ('Diverter Location');
insert into attributes (description) values ('Down Pipe');
insert into attributes (description) values ('Drain Assembly Included');
insert into attributes (description) values ('Eco Friendly');
insert into attributes (description) values ('Electronic');
insert into attributes (description) values ('Escutcheon Height');
insert into attributes (description) values ('Escutcheon Included');
insert into attributes (description) values ('Escutcheon Width');
insert into attributes (description) values ('Everclean');
insert into attributes (description) values ('Extension');
insert into attributes (description) values ('Faucet Centers');
insert into attributes (description) values ('Faucet Hole Size');
insert into attributes (description) values ('Faucet Holes');
insert into attributes (description) values ('Faucet Type');
insert into attributes (description) values ('Filtering');
insert into attributes (description) values ('Flow Rate (Gpm)');
insert into attributes (description) values ('Flowise');
insert into attributes (description) values ('Handle Height');
insert into attributes (description) values ('Handle Material');
insert into attributes (description) values ('Handle Style');
insert into attributes (description) values ('Handles Included');
insert into attributes (description) values ('Handshower');
insert into attributes (description) values ('Handshower Flow Rate');
insert into attributes (description) values ('Handshower Included');
insert into attributes (description) values ('Hole Size');
insert into attributes (description) values ('Hose Included');
insert into attributes (description) values ('Hose Length');
insert into attributes (description) values ('Inlet/Outlet Size');
insert into attributes (description) values ('Installation Type');
insert into attributes (description) values ('Integrated Diverter');
insert into attributes (description) values ('Low Lead Compliant');
insert into attributes (description) values ('Manufacturer Warranty');
insert into attributes (description) values ('Material');
insert into attributes (description) values ('Max Deck Thickness');
insert into attributes (description) values ('Mounting Hardware Included');
insert into attributes (description) values ('Mounting Type');
insert into attributes (description) values ('Nsf Approved');
insert into attributes (description) values ('Number Of Handles');
insert into attributes (description) values ('Number Of Ports');
insert into attributes (description) values ('Number Of Shower Heads');
insert into attributes (description) values ('Overall Height');
insert into attributes (description) values ('Overall Width');
insert into attributes (description) values ('Overflow');
insert into attributes (description) values ('Pop-Up Included');
insert into attributes (description) values ('Pre Rinse');
insert into attributes (description) values ('Pressure Balanced');
insert into attributes (description) values ('Product Weight');
insert into attributes (description) values ('Pullout Direction');
insert into attributes (description) values ('Pullout Spray');
insert into attributes (description) values ('Scald Guard');
insert into attributes (description) values ('Series');
insert into attributes (description) values ('Shape');
insert into attributes (description) values ('Shower Arm Reach');
insert into attributes (description) values ('Showerhead');
insert into attributes (description) values ('Showerhead Flow Rate');
insert into attributes (description) values ('Showerhead Flow Rate (Gpm)');
insert into attributes (description) values ('Showerhead Height');
insert into attributes (description) values ('Showerhead Projection');
insert into attributes (description) values ('Showerhead Shape');
insert into attributes (description) values ('Showerhead Width');
insert into attributes (description) values ('Sidespray');
insert into attributes (description) values ('Sidespray Height');
insert into attributes (description) values ('Slide Bar Included');
insert into attributes (description) values ('Soap Dispenser Included');
insert into attributes (description) values ('Speed Connect');
insert into attributes (description) values ('Spout Height');
insert into attributes (description) values ('Spout Reach');
insert into attributes (description) values ('Spout Swivel');
insert into attributes (description) values ('Spout Type');
insert into attributes (description) values ('Spray Pattern');
insert into attributes (description) values ('Spray Settings');
insert into attributes (description) values ('Theme');
insert into attributes (description) values ('Tub Spout Reach');
insert into attributes (description) values ('Upc Approved');
insert into attributes (description) values ('Valve Included');
insert into attributes (description) values ('Valve Type');
insert into attributes (description) values ('Vandal Resistant Screws');
insert into attributes (description) values ('Voltage');
insert into attributes (description) values ('Volume Control');
insert into attributes (description) values ('Wall Supply Included');
insert into attributes (description) values ('Water Efficient');
insert into attributes (description) values ('Watersense Certified');
